version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: petrem/tut_hello:part-2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8008"
    networks:
      - webnet
networks:
  webnet:
