name: collatz-conjecture
version: 1.2.1.4

dependencies:
  - base
  - extra
  - mtl

library:
  exposed-modules:
    - CollatzConjecture
    - CollatzConjectureRecursive
    - CollatzConjectureHigherOrder
  source-dirs: src
  ghc-options: -Wall -O2
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

executables:
  collatz-bench:
    main: Main.hs
    source-dirs: app
    ghc-options: -O2
    dependencies:
    - collatz-conjecture

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec
