name:                yacht
version:             1.2.0.0

dependencies:
  - base
  - containers

library:
  exposed-modules: Yacht
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  #   - foo


tests:
  test:
    main:        Tests.hs
    source-dirs: test
    dependencies:
    - yacht
    - hspec
